### ISSUE TITLE
Fix server response error in crop prediction feature

### ISSUE THREAD

**Issue by varchanaiyer** [lsvishawjeet/AgriTechProject#1]
![image](https://github.com/user-attachments/assets/74c152d2-0468-40bb-8948-4cb9439e4803)
The crop prediction feature is currently returning a server error. Debug and resolve the issue to ensure reliable predictions.

**Comment by lsvishawjeet** [comment]
It is now fixed. Check it out [here](https://agritechai.vercel.app/home)
