### ISSUE TITLE
Add user authentication and prediction history feature

### ISSUE THREAD

**Issue by varchanaiyer** [lsvishawjeet/AgriTechProject#2]
Implement user accounts and allow users to save and view their past crop predictions.

**Comment by lsvishawjeet** [comment]
Users can now log in to access and review the history of their previously entered details. I've added the option to log in using Google and GitHub accounts, ensuring that the app can only be accessed by authenticated users.

Please feel free to log in and test the feature. Let me know if there are any further adjustments or enhancements you'd like to see.

**Comment by lsvishawjeet** [comment]
Mam, I have completed the integration of user authentication into the project as requested. Users can now log in to access and review the history of their previously entered details. I've added the option to log in using Google and GitHub accounts, ensuring that the app can only be accessed by authenticated users.

Please feel free to [login](https://agritechai.vercel.app/) and test the feature. Let me know if there are any further adjustments or enhancements you'd like to see.
